$path = 'D:\Projects\fraud_model\docs\UI_IMPLEMENTATION_FINDINGS.md'
$content = @'
- **Model artifacts (all in `models_artifacts/`, all real):**
  - `xgboost_tier1.json` (frozen baseline, 541 KB) -- **primary detector**
  - `xgboost_tier1_feedback.json` (541 KB) -- closed-loop variant
  - `xgboost_tier1_smotenc.json` (533 KB) -- SMOTENC variant
  - `isolation_forest_tier2.joblib` (3.0 MB) -- near-random, documented honestly
  - `shap_importance_bar.png`, `shap_summary_beeswarm.png`, `shap_waterfall_detected.png`, `shap_waterfall_impersonation.png` (existing static SHAP viz)
- **`src/models/explain.py`** -- `shap.TreeExplainer(model); shap_values = explainer(X_test)` produces `Explanation` objects; `additivity_self_check` validates `margin ~= base + sum(SHAP)`. **To use per-tx on the API, we need a new function -- the current one only writes PNGs.**

### 1.4 Feedback loop -- the strongest story
- **`src/models/feedback_loop.py`** -- `MAX_CYCLES = FEEDBACK_MAX_CYCLES = 5` (cycle 0 = diagnose, 1..4 = retrain). Saves `xgboost_tier1_feedback.json` and `synthetic_feedback_rows.csv` (1.1 MB, audit trail).
- **`src/models/failure_analyzer.py`** -- aggregates missed-pattern stats per fraud type (per-feature medians + category frequencies; **no individual val row ever copied**).
- **Real, measured numbers (from `CHANGELOG.md` v1.1.0):**
  - Val recall: **0.8200 -> 0.8467** across cycles
  - One-shot test: recall **0.7834 -> 0.7962**, FN **34 -> 32**, PR-AUC **0.9072 -> 0.9089**
  - Precision: **0.9044 -> 0.8562** (frozen threshold moved 0.96 -> 0.94 -- operating-point choice, disclosed honestly)
- **These numbers go on the Loop page as the headline proof.**

### 1.5 Web prototype -- currently broken
- **`app.py`** (Streamlit, 7.6 KB):
  - **Syntactically broken:** lines 51-60 declare `with col1, col2` inside the Overview page, but the body of `col2` (lines 173-188) is *stranded after the footer at line 171*. Will raise on import.
  - **"Live Demo" tab does not call the model:** it does `if amount > 5000: risk_score += 0.3` -- a hardcoded heuristic.
  - Pages: Overview / Attack Taxonomy / Model Performance / Live Demo / Feedback Loop.
- **`package.json`** has only `graphifyy` + `@playwright/test`. No frontend framework.

### 1.6 Data on disk (what the UI can show)
- `data/raw/transactions.csv` -- **1,064,963 transactions** (confirmed). Schema: `transaction_id,user_id,timestamp,amount,merchant_id,merchant_category,device_id,lat,lon,channel,account_age_days,is_fraud,fraud_type,case_id,ring_id,three_ds_result,three_ds_failures_before_result`.
- `data/processed/` -- 11 pickle/csv files for train/val/test splits and X matrices.
- `models_artifacts/isolation_forest_thresholds.csv` -- 7 rows of contamination/threshold tradeoffs; the Loop page can show this.
- `models_artifacts/isolation_forest_config.json` -- `{best_structural_params, final_contamination, frozen_threshold, val_pr_auc: 0.0052, test_pr_auc: 0.0069}`.
- `data/processed/synthetic_feedback_rows.csv` -- **1,136,595 bytes** of synthetic adversarial rows generated by the feedback loop.
- `data/processed/anomaly_feedback_queue.csv` -- the queue the IF2 disagreement signal feeds.

---
'@
Add-Content -Path $path -Value $content -Encoding UTF8
Write-Output "Part 2b added: $((Get-Item $path).Length) chars total"
